name: File Diff

on:
  pull_request:
    branches: ['*']

jobs:
  filediff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: File Diff
      uses: Shopify/filediff@v0.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: ${{ github.base_ref }}
        dir_glob: '**/*.py,**/*.md,**/*.yml,**/*.yaml'
        pre_diff_script: |
          echo "Running pre-diff setup..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        file_details_open: false
        replace_comment: true
